{
 "title": "Fraud Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Flagged Fraudulent transactions",
   "type": "stat",
   "description": "Number of transactions believed to be fraudulent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "Select count(*) AS fraudulant_transactions from transactions where fraudulent = 1;"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "description": "Total number of Transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "Select count(*) as total_transactions from transactions;"
    }
   ]
  },
  {
   "title": "fraud ordered by state",
   "type": "barchart",
   "description": "Transactions flagged as being fraudulent ordered by the location they took place",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "select substring_index(substring_index(location, ' ', -2), ' ', 1) as state, count(*) as fraud_amount from transactions group by location  desc limit 5;"
    }
   ]
  }
 ]
}