{
 "title": "Fraud Dashboard",
 "time": { "from": "2023-12-31T08:00:00.000Z", "to": "2024-07-26T06:59:59.000Z" },
 "panels": [
  {
   "title": "Total Transaction Count",
   "type": "stat",
   "description": "Total Number of Legitimate and Fraudulent Transactions during the time period specified.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "SELECT COUNT(*) as 'Legitimate'\r\nFROM transactions\r\nWHERE fraudulent != 1 and transaction_date BETWEEN $__timeFrom() AND $__timeTo();"
    },
    {
     "dataset": "fraud_detection",
     "rawSql": "SELECT COUNT(*) as 'Fraudulent'\r\nFROM transactions\r\nWHERE fraudulent = 1 AND transaction_date BETWEEN $__timeFrom() AND $__timeTo();"
    }
   ]
  },
  {
   "title": "Fraud Rate From all Transactions",
   "type": "stat",
   "description": "The percentage of transactions flagged as fraudulent from the dataset.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "select round(sum(fraudulent) / count(*) * 100, 2) as 'fraud rate' from transactions WHERE transaction_date BETWEEN $__timeFrom() AND $__timeTo() ;"
    }
   ]
  },
  {
   "title": "Transactions over time",
   "type": "timeseries",
   "description": "Time series representing transactions over time grouped by month",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "SELECT DATE(transaction_date) AS date, COUNT(*) AS transaction_count\r\nFROM transactions WHERE transaction_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY DATE(transaction_date)\r\nORDER BY DATE(transaction_date);"
    }
   ]
  },
  {
   "title": "Fraud Rate by Month",
   "type": "bargauge",
   "description": "Bar gauge representing the fraud rate for all transactions during the months displayed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "SELECT DATE_FORMAT(transaction_date, '%Y-%m') AS month, \r\n       SUM(fraudulent) / COUNT(*) AS fraud_rate\r\nFROM transactions WHERE transaction_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY DATE_FORMAT(transaction_date, '%Y-%m')\r\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Fraud Rate Percentage by Region",
   "type": "table",
   "description": "Table that groups transactions by zip code, showing the count of fraudulent records and fraud rate percentage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "SELECT\r\n  SUBSTRING_INDEX(location, ' ', -1) AS `zip code`,\r\n  COUNT(*) AS `record count`,\r\n  CONCAT(round(AVG(fraudulent) * 100, 2), '%') AS `fraud rate percentage`\r\nFROM transactions\r\nWHERE transaction_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY `zip code`\r\nORDER BY `record count` DESC;"
    }
   ]
  },
  {
   "title": "Transactions and Fraud Rate Ordered by Month",
   "type": "barchart",
   "description": "Bar chart that displays the total number of legitimate transactions, fraudulent transactions, and fraud rate for each month within the time range given.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "SELECT DATE_FORMAT(transaction_date, '%Y-%m') AS transaction_month,\r\n       COUNT(*) AS 'Total Transactions',\r\n       SUM(fraudulent) AS 'Total Fraudulent Transactions',\r\n       (SUM(fraudulent) / COUNT(*)) * 100 AS 'Fraud Rate'\r\nFROM transactions WHERE transaction_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY transaction_month\r\nORDER BY transaction_month;"
    }
   ]
  },
  {
   "title": "Fraudulent Transactions by Day of Week",
   "type": "barchart",
   "description": "Bar chart representing fraudulent transactions ordered by day of the week it occurred",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "SELECT DAYNAME(transaction_date) AS `Day of Week`,\r\nCOUNT(*) AS 'Fraudulent Transactions'\r\nFROM transactions\r\nWHERE fraudulent = 1\r\nAND transaction_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY `Day of Week`\r\nORDER BY FIELD(`Day of Week`, 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');"
    }
   ]
  },
  {
   "title": "Fraudulent Transactions Grouped by Cause",
   "type": "piechart",
   "description": "Pie chart that represents the cause of transactions being marked fraudulent. Scrolling over the chart will the show the transactions count for each type of transaction.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fraud_detection",
     "rawSql": "SELECT\r\n    CASE \r\n        WHEN merchant LIKE '%Ltd%' THEN 'Merchant Contains \"Ltd\"'\r\n        WHEN amount > 700 THEN 'Amount Exceeds $700'\r\n        ELSE 'Unknown'\r\n    END AS Cause,\r\n    COUNT(*) AS 'Records found'\r\nFROM transactions\r\nWHERE fraudulent = 1 and transaction_date BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY Cause;"
    }
   ]
  }
 ]
}